all: code
	mkdir -p ../../data/mods/timetravel
	cp -r textures ../../data/mods/timetravel
	cp config.json ../../data/mods/timetravel
code:
	mkdir -p ../../data/mods/timetravel/src
	cp -r src ../../data/mods/timetravel
	cp main.lua ../../data/mods/timetravel/main.lua
clean:
	rm -rf ../../data/mods/timetravel
